### ISSUE TITLE
League doesn’t exist

### ISSUE THREAD

**Issue by Ktrap9** [jeisey/commish#1]
I am inputting all of the correct information but it is telling me that my league doesn’t exist. How do u fix this?

**Comment by BraxtonLanc43** [comment]
I'm receiving the same error. First time trying to use this tool.

**Comment by jeisey** [comment]
Are you using Yahoo, Sleeper, or ESPN leagues?

**Comment by BraxtonLanc43** [comment]
ESPN League. 
Chrome browser, without the recommended extension enabled (just following manual instructions). 
Logged into ESPN. 

I’ll see if I can try again later and capture anything  else that was in console or something.

**Comment by jeisey** [comment]
@BraxtonLanc43 ESPN and Yahoo should be resolved now. Let me know if it's working for you when you get a chance. Sleeper still has some issues with a wrapper I forked last year.

**Comment by BraxtonLanc43** [comment]
@jeisey Confirmed I'm able to run this now. Thanks! This is great, cheers.
